assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDeployment
continuous-delivery-fallback-tag: "Canary"
next-version: 1.0.0
branches:
  main:
    mode: ContinuousDeployment
    tag: "preview"
    increment: Patch
    is-mainline: true
    prevent-increment-of-merged-branch-version: false
    tracks-release-branches: true
    regex: ^master$|^main$
  release:
    mode: ContinuousDelivery
    tag: ""
    increment: Patch
    track-merge-target: false
    regex: ^release(s)?[\/-]
    source-branches:
      - master
      - main
    is-release-branch: true
    is-mainline: false
ignore:
  sha: []
merge-message-formats: {}
